# Autogenerated wrapper script for GAP_pkg_profiling_jll for aarch64-linux-gnu-cxx03
export profiling

using GAP_jll
JLLWrappers.@generate_wrapper_header("GAP_pkg_profiling")
JLLWrappers.@declare_file_product(profiling)
function __init__()
    JLLWrappers.@generate_init_header(GAP_jll)
    JLLWrappers.@init_file_product(
        profiling,
        "lib/gap/profiling.so",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
